<script lang="ts">
	import Router from "./lib/Nav/ClientSideRouter.svelte";
	import Route from "./lib/Nav/Route.svelte";
	import Redirect from "./lib/Redirect.svelte";
	import Tysnd from "./lib/TYSND.svelte";

	async function getCatalogue() {
		const res = await fetch(`/data/catalogue.json`);
		const values = await res.json();

		return values;
	}

	let cataloguePromise = getCatalogue();
</script>

<main>
	<Router>
		{#await cataloguePromise}
			<!-- Default shit -->
		{:then catalogue}
			<Route path={"/"}>
				<Redirect path={`/part/${catalogue.latest}`} />
			</Route>
			<Route path={"/part/{part}"}>
				<Tysnd
					all_catalogue={catalogue.all}
					latestPart={catalogue.latest}
				/>
			</Route>
		{:catch error}
			{"Not ready yet! ;)"}
		{/await}
	</Router>

	<br />

	<div class="footer">
	Come back daily for more Things You Should Not Do! <br/>
	These lists are generated by GPT-3 and may not have been reviewed by a human - opinions are not my own.<br />
	View the <a href="https://github.com/CamerAllan/things-you-should-not-do">source</a>. <br/>
	Based on <a href={"https://xkcd.com/2669/"}>this comic</a> by XKCD.<br/>
	Maintained by <a href="https://github.com/CamerAllan">Cameron Allan</a>. <br />
	</div>
</main>

<style>
	
	.footer {
		text-align: center;
	}

	@font-face {
		font-family: "xkcd";
		src: url("/fonts/xkcd-script.ttf");
	}
</style>
